// THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Bearer Act Sections Data
export const hinduAdoptionsMaintenanceBearerActSections = [
  {
    "section": "Section 1",
    "sectionNo": "1",
    "chapterNo": 1,
    "chapterRoman": "I",
    "chapterName": "PRELIMINARY",
    "title": "Short title and extent.",
    "description": "1. Short title and extent.―(1)This Act may be called the Hindu Adoptions and Maintenance Act, 1956.\n(2) It extends to the whole of India 2***.",
    "metaData": "PRELIMINARY",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 1 - Short title and extent.",
    "metaTitle": "Section 1 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 2",
    "sectionNo": "2",
    "chapterNo": 1,
    "chapterRoman": "I",
    "chapterName": "PRELIMINARY",
    "title": "Application of Act.",
    "description": "2. Application of Act.―(1) This Act applies―\n(a) to any person, who is a Hindu by religion in any of its forms or developments, including a Virashaiva, a Lingayat or a follower of the Brahmo, Prarthana or AryaSamaj,\n(b) to any person who is a Buddhist, Jaina or Sikh by religion, and\n(c) to any other person who is not a Muslim, Christian, Parsi or Jew by religion, unless it is proved that any such person would not have been governed by the Hindu law or by any custom or usage as part of that law in respect of any of the matters dealt with herein if this Act had not been passed.\nExplanation.―The following persons are Hindus, Buddhists, Jainas or Sikhs by religion, as the case may be:―\n(a) any child, legitimate or illegitimate, both of whose parents are Hindus, Buddhists, Jainas or Sikhs by religion;\n(b) any child, legitimate or illegitimate, one of whose parents is a Hindu, Buddhist, Jaina or Sikh by religion and who is brought up as a member of the tribe, community, group or family to which such parent belongs or belonged; 3* * *\n4[(bb) any child, legitimate or illegitimate, who has been abandoned both by his father and mother or whose parentage is not known and who in either case is brought up as a Hindu, Buddhist, Jaina or Sikh; and]\n(c) any person who is a convert or re-convert to the Hindu, Buddhist, Jaina or Sikh religion.\n(2) Notwithstanding anything contained in sub-section (1), nothing contained in this Act shall apply to the members of any Scheduled Tribe within the meaning of clause (25) of article 366 of the Constitution unless the Central Government, by notification in the Official Gazette, otherwise directs.\n(3) The expression “Hindu” in any portion of this Act shall be construed as if it included a person who, though not a Hindu by religion, is, nevertheless, a person to whom this Act applies by virtue of the provisions contained in this section.",
    "metaData": "PRELIMINARY",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 2 - Application of Act.",
    "metaTitle": "Section 2 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 3",
    "sectionNo": "3",
    "chapterNo": 1,
    "chapterRoman": "I",
    "chapterName": "PRELIMINARY",
    "title": "Definitions.",
    "description": "3. Definitions.―In this Act, unless the context otherwise requires,―\n(a) the expressions “custom” and “usage” signify any rule which, having been continuously and uniformly observed for a long time, has obtained the force of law among Hindus in any local area, tribe, community, group or family:\nProvided that the rule is certain and not unreasonable or opposed to public policy: and\nProvided further that, in the case of a rule applicable only to a family, it has not been discontinued by the family;\n(b) “maintenance” includes―\n(i) in all cases, provision for food, clothing, residence, education and medical attendance and treatment;\n(ii) in the case of an unmarried daughter, also the reasonable expenses of and incident to her marriage;\n(c) “minor” means a person who has not completed his or her age of eighteen years.",
    "metaData": "PRELIMINARY",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 3 - Definitions.",
    "metaTitle": "Section 3 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 4",
    "sectionNo": "4",
    "chapterNo": 1,
    "chapterRoman": "I",
    "chapterName": "PRELIMINARY",
    "title": "Overriding effect of Act.",
    "description": "4.Overriding effect of Act.―Save as otherwise expressly provided in this Act,―\n(a) any text, rule or interpretation of Hindu law or any custom or usage as part of that law in force immediately before the commencement of this Act shall cease to have effect with respect to any matter for which provision is made in this Act;\n(b) any other law in force immediately before the commencement of this Act shall cease to apply to Hindus in so far as it is inconsistent with any of the provisions contained in this Act.",
    "metaData": "PRELIMINARY",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 4 - Overriding effect of Act.",
    "metaTitle": "Section 4 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 5",
    "sectionNo": "5",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Adoptions to be regulated by this Chapter.",
    "description": "5.Adoptions to be regulated by this Chapter.―(1)No adoption shall be made after the commencement of this Act by or to a Hindu except in accordance with the provisions contained in this Chapter, and any adoption made in contravention of the said provisions shall be void.\n(2) An adoption which is void shall neither create any rights in the adoptive family in favour of any person which he or she could not have acquired except by reason of the adoption, nor destroy the rights of any person in the family of his or her birth.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 5 - Adoptions to be regulated by this Chapter.",
    "metaTitle": "Section 5 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 6",
    "sectionNo": "6",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Requisites of a valid adoption.",
    "description": "6. Requisites of a valid adoption.―No adoption shall be valid unless—\n(i) the person adopting has the capacity, and also the right, to take in adoption;\n(ii) the person giving in adoption has the capacity to do so;\n(iii) the person adopted is capable of being taken in adoption; and\n(iv) the adoption is made in compliance with the other conditions mentioned in this Chapter.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 6 - Requisites of a valid adoption.",
    "metaTitle": "Section 6 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 7",
    "sectionNo": "7",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Capacity of a male Hindu to take in adoption.",
    "description": "7.Capacity of a male Hindu to take in adoption.―Any male Hindu who is of sound mind and is not a minor has the capacity to takes on or a daughter in adoption:\nProvided that, if he has a wife living, he shall not adopt except with the consent of his wife unless the wife has completely and finally renounced the word or has ceased to be a Hindu or has been declared by a court of competent jurisdiction to be of unsound mind.\nExplanation.―If a person has more than one wife living at the time of adoption, the consent of all the wives is necessary unless the consent of any one of them is unnecessary for any of the reasons specified in the preceding proviso.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 7 - Capacity of a male Hindu to take in adoption.",
    "metaTitle": "Section 7 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 8",
    "sectionNo": "8",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Capacity of a female Hindu to take in adoption.",
    "description": "1[8.Capacity of a female Hindu to take in adoption.―Any female Hindu who is of sound mind and is not a minor has the capacity to take a son or daughter in adoption:\nProvided that, if she has a husband living, she shall not adopt a son or daughter except with the consent of her husband unless the husband has completely and finally renounced the world or has ceased to be a Hindu or has been declared by a court of competent jurisdiction to be of unsound mind.]",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 8 - Capacity of a female Hindu to take in adoption.",
    "metaTitle": "Section 8 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 9",
    "sectionNo": "9",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Persons capable of giving in adoption.",
    "description": "9.Persons capable of giving in adoption.―(1)No person except the father or mother or the guardian of a child shall have the capacity to give the child in adoption.\n2[(2) Subject to the provisions of sub-section (4), the father or the mother, if alive, shall have equal right to give a son or daughter in adoption:\nProvided that such right shall not be exercised by either of them save with the consent of the other unless one of them has completely and finally renounced the world or has ceased to be a Hindu or has been declared by a court of competent jurisdiction to be of unsound mind.]\n3* * * * *\n4[(4) Where both the father and mother are dead or have completely and finally renounced the world or have abandoned the child or have been declared by a court of competent jurisdiction to be of unsound mind or where the parentage of the child is not known, the guardian of the child may give the child in adoption with the previous permission of the court to any person including the guardian himself.]\n(5) Before granting permission to a guardian under sub-section (4), the court shall be satisfied that the adoption will be for the welfare of the child, due consideration being for this purpose given to the wishes of the child having regard to the age and understanding of the child and that the applicant for permission has not received or agreed to receive and that no person has made or given or agreed to make or give to the applicant any payment or reward in consideration of the adoption except such as the court may sanction.\nExplanation.―For the purposes of this section―\n(i) the expressions “father” and “mother” do not include an adoptive father and an adoptive mother; 5* * *\n6[(ia) “guardian” means a person having the care of the person of a child or of both his person and property and includes―\n(a) a guardian appointed by the will of the child's father or mother, and\n(b) a guardian appointed or declared by a court; and]\n(ii) “court” means the city civil court or a district court within the local limits of whose jurisdiction the child to be adopted ordinarily resides.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 9 - Persons capable of giving in adoption.",
    "metaTitle": "Section 9 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 10",
    "sectionNo": "10",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Persons who may be adopted.",
    "description": "10. Persons who may be adopted.―No person shall be capable of being taken in adoption unless the following conditions are fulfilled, namely:―\n(i) he or she is a Hindu;\n(ii) he or she has not already been adopted;\n(iii) he or she has not been married, unless there is a custom or usage applicable to the parties which permits persons who are married being taken in adoption;\n(iv) he or she has not completed the age of fifteen years, unless there is a custom or usage applicable to the parties which permits persons who have completed the age of fifteen years being taken in adoption.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 10 - Persons who may be adopted.",
    "metaTitle": "Section 10 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 11",
    "sectionNo": "11",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Other conditions for a valid adoption.",
    "description": "11.Other conditions for a valid adoption.―In every adoption, the following conditions must be complied with:―\n(i) if the adoption is of a son, the adoptive father or mother by whom the adoption is made must not have a Hindu sonson’s son or son’s son’s son (whether by legitimate blood relationship or by adoption) living at the time of adoption;\n(ii) if the adoption is of a daughter, the adoptive father or mother by whom the adoption is made must not have a Hindu daughter or son’s daughter (whether by legitimate blood relationship or by adoption) living at the time of adoption;\n(iii) if the adoption is by a male and the person to be adopted is a female, the adoptive father is at least twenty-one years older than the person to be adopted;\n(iv) if the adoption is by a female and the person to be adopted is a male, the adoptive mother is at least twenty-one years older than the person to be adopted;\n(v) the same child may not be adopted simultaneously by two or more persons;\n(vi) the child to be adopted must be actually given and taken in adoption by the parents or guardian concerned or under their authority with intent to transfer the child from the family of its birth 1[or in the case of an abandoned child or a child whose parentage is not known, from the place or family where it has been brought up] to the family of its adoption:\nProvided that the performance of dattahomam shall not be essential to the validity of an adoption.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 11 - Other conditions for a valid adoption.",
    "metaTitle": "Section 11 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 12",
    "sectionNo": "12",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Effects of adoption.",
    "description": "12.Effects of adoption.―An adopted child shall be deemed to be the child of his or her adoptive father or mother for all purposes with effect from the date of the adoption and from such date all the ties of the child in the family of his or her birth shall be deemed to be severed and replaced by those created by the adoption in the adoptive family:\nProvided that―\n(a) the child cannot marry any person whom he or she could not have married if he or she had continued in the family of his or her birth;\n(b) any property which vested in the adopted child before the adoption shall continue to vest in such person subject to the obligations, if any, attaching to the ownership of such property, including the obligation to maintain relatives in the family of his or her birth;\n(c) the adopted child shall not divest any person of any estate which vested in him or her before the adoption.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 12 - Effects of adoption.",
    "metaTitle": "Section 12 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 13",
    "sectionNo": "13",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Right of adoptive parents to dispose of their properties.",
    "description": "13. Right of adoptive parents to dispose of their properties.―Subject to any agreement to the contrary, an adoption does not deprive the adoptive father or mother of the power to dispose of his or her property by transfer inter vivos or by will.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 13 - Right of adoptive parents to dispose of their properties.",
    "metaTitle": "Section 13 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 14",
    "sectionNo": "14",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Determination of adoptive mother in certain cases.",
    "description": "14. Determination of adoptive mother in certain cases.―(1)Where aHindu who has a wife living adopts a child, she shall be deemed to bethe adoptive mother.\n(2) Where an adoption has been made with the consent of more than one wife, the seniormost in marriage among them shall be deemed to be the adoptive mother and the others to be step-mothers.\n(3) Where a widower or a bachelor adopts a child, any wife whom he subsequently marries shall be deemed to be the step-mother of the adopted child.\n(4) Where a window or an unmarried woman adopts a child, any husband whom she marries subsequently shall be deemed to be the step-father of the adopted child.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 14 - Determination of adoptive mother in certain cases.",
    "metaTitle": "Section 14 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 15",
    "sectionNo": "15",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Valid adoption not to be cancelled.",
    "description": "15. Valid adoption not to be cancelled.―No adoption which has been validly made can be cancelled by the adoptive father or mother or any other person, nor can the adopted child renounce his or her status as such and return to the family of his or her birth.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 15 - Valid adoption not to be cancelled.",
    "metaTitle": "Section 15 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 16",
    "sectionNo": "16",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Presumption as to registered documents relating to adoption.",
    "description": "16. Presumption as to registered documents relating to adoption.―Whenever any document registered under any law for the time being in force is produced before any court purporting to record an adoption made and is signed by the person giving and the person taking the child in adoption, the court shall presume that the adoption has been made in compliance with the provisions of this Act unless and until it is disproved.\n\nSTATE AMENDMENT\nUttar Pradesh\nAmendment of section 16 of Act 78 of 1956.—In the Hindu Adaptation and Maintenance Act, 1956, section 16 shall be re-numbered as sub-section (1) thereof, and after sub-section (1) as so re-numbered the following sub-section shall be inserted namely:--\n“(2) In case any adoption made on or after the first day of January, 1977 no Court in Uttar Pradesh shall accept any evidence in proof of the giving and taking of the child in adoption, except a document recording an adoption, made and signed by the person giving and the person taking the child in adoption, and registered under any law for the time being in force;\nProvided that secondary evidence of such document shall be admissible in the circumstances and the manner laid down in the Indian Evidence Act, 1872 (1 of 1872).”.\n[Vide Uttar Pradesh Act 57 of 1976, s. 35]",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 16 - Presumption as to registered documents relating to adoption.",
    "metaTitle": "Section 16 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 17",
    "sectionNo": "17",
    "chapterNo": 2,
    "chapterRoman": "II",
    "chapterName": "ADOPTION",
    "title": "Prohibition of certain payments.",
    "description": "17. Prohibition of certain payments.―(1)No person shall receive or agree to receive any payment or other reward in consideration of the adoption of any person, and no person shall make or give or agree to make or give to any other person any payment or reward the receipt of which is prohibited by this section.\n(2) If any person contravenes the provisions of sub-section (1), he shall be punishable with imprisonment which may extend to six months, or with fine, or with both.\n(3) No prosecution under this section shall be instituted without the previous sanction of the State Government or an officer authorised by the State Government in this behalf.",
    "metaData": "ADOPTION",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 17 - Prohibition of certain payments.",
    "metaTitle": "Section 17 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 18",
    "sectionNo": "18",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Maintenance of wife.",
    "description": "18. Maintenance of wife.―(1)Subject to the provisions of this section, a Hindu wife, whether married before or after the commencement of this Act, shall be entitled to be maintained by her husband during her life time.\n(2) A Hindu wife shall be entitled to live separately from her husband without forfeiting her claim to maintenance,―\n(a) if he is guilty of desertion, that is to say, of abandoning her without reasonable cause and without her consent or against her wish, or of wilfully neglecting her;\n(b) if he has treated her with such cruelty as to cause a reasonable apprehension in her mind that it will be harmful or injurious to live with her husband;\n1* * * * *\n(d) if he has any other wife living;\n(e) if he keeps a concubine in the same house in which his wife is living or habitually resides with a concubine elsewhere;\n(f) if he has ceased to be a Hindu by conversion to another religion;\n(g) if there is any other cause justifying her living separately.\n(3) A Hindu wife shall not be entitled to separate residence and maintenance from her husband if she is unchaste or ceases to be a Hindu by conversion to another religion.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 18 - Maintenance of wife.",
    "metaTitle": "Section 18 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 19",
    "sectionNo": "19",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Maintenance of widowed daughter-in-law.",
    "description": "19. Maintenance of widowed daughter-in-law.―(1) A Hindu wife, whether married before or after the commencement of this Act, shall be entitled to be maintained after the death of her husband by her father-in-law:\nProvided and to the extent that she is unable to maintain herself out of her own earnings or other property or, where she has no property of her own, is unable to obtain maintenance―\n(a) from the estate of her husband or her father or mother, or\n(b) from her son or daughter, if any, or his or her estate.\n(2) Any obligation under sub-section (1) shall not be enforceable if the father-in-law has not the means to do so from any coparcenary property in his possession out of which the daughter-in- law has not obtained any share, and any such obligation shall cease on the remarriage of the daughter-in-law.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 19 - Maintenance of widowed daughter-in-law.",
    "metaTitle": "Section 19 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 20",
    "sectionNo": "20",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Maintenance of children and aged parents.",
    "description": "20. Maintenance of children and aged parents.―(1)Subject to the provisions of this section a Hindu is bound, during his or her life-time, to maintain his or her legitimate or illegitimate children and his or her aged or infirm parents.\n(2) A legitimate or illegitimate child may claim maintenance from his or her father or mother so long as the child is a minor.\n(3) The obligation of a person to maintain his or her aged or infirm parent or a daughter who is unmarried extends in so far as the parent or the unmarried daughter, as the case may be, is unable to maintain himself or herself out of his or her own earnings or other property.\nExplanation.―In this section “parent “includes a childless step-mother.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 20 - Maintenance of children and aged parents.",
    "metaTitle": "Section 20 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 21",
    "sectionNo": "21",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Dependants defined.",
    "description": "21. Dependants defined.―For the purposes of this Chapter “dependants” mean the following relatives of the deceased:―\n(i) his or her father;\n(ii) his or her mother;\n(iii) his widow, so long as she does not re-marry;\n(iv) his or her son or the son of his predeceased son or the son of a predeceased son of his pre-deceased son, so long as he is a minor: provided and to the extent that he is unable to obtain maintenance, in the case of a grandson from his father’s or mother’s estate, and in the case of a great-grandson, from the estate of his father or mother or father’s father or father’s mother;\n(v) his or her unmarried daughter, or the unmarried daughter of his predeceased son or the unmarried daughter of a predeceased son of his predeceased son, so long as she remains unmarried:provided and to the extent that she is unable to obtain maintenance, in the case of a grand-daughter from her father’s or mother’s estate and in the case of a great-grand-daughter from the estate of her father or mother or father's father or father’s mother;\n(vi) his widowed daughter: provided and to the extent that she is unable to obtain maintenance―\n(a) from the estate of her husband; or\n(b) from her son or daughter if any, or his or her estate; or\n(c) from her father-in-law or his father or the estate of either of them;\n(vii) any widow of his son or of a son of his predeceased son, so long as she does not re-marry: provided and to the extent that she is unable to obtain maintenance from her husband’s estate, or from her son or daughter, if any, or his or her estate; or in the case of a grandson’s widow, also from her father-in-law’s estate;\n(viii) his or her minor illegitimate son, so long as he remains a minor;\n(ix) his or her illegitimate daughter, so long as she remains unmarried.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 21 - Dependants defined.",
    "metaTitle": "Section 21 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 22",
    "sectionNo": "22",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Maintenance of dependants.",
    "description": "22. Maintenance of dependants.―(1) Subject to the provisions of sub-section (2), the heirs of a deceased Hindu are bound to maintain the dependants of the deceased out of the estate inherited by them from the deceased.\n(2) Where a dependant has not obtained, by testamentary or intestate succession, any share in the estate of a Hindu dying after the commencement of this Act, the dependant shall be entitled, subject to the provisions of this Act, to maintenance from those who take the estate.\n(3) The liability of each of the persons who takes the estate shall be in proportion to the value of the share or part of the estate taken by him or her.\n(4) Notwithstanding anything contained in sub-section (2) or sub-section (3), no person who is himself or herself a dependant shall be liable to contribute to the maintenance of others, if he or she has obtained a share or part the value of which is, or would, if the liability to contribute were enforced, become less than what would be awarded to him or her by way of maintenance under this Act.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 22 - Maintenance of dependants.",
    "metaTitle": "Section 22 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 23",
    "sectionNo": "23",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Amount of maintenance.",
    "description": "23. Amount of maintenance.―(1) It shall be in the discretion of the court to determine whether any, and if so what, maintenance shall be awarded under the provisions of this Act, and in doing so the court shall have due regard to the considerations set out in sub-section (2) or sub-section (3), as the case may be, so far as they are applicable.\n(2) In determining the amount of maintenance, if any, to be awarded to a wife, children or aged on infirm parents under this Act, regard shall be had to―\n(a) the position and status of the parties;\n(b) the reasonable wants of the claimant;\n(c) if the claimant is living separately, whether the claimant is justified in doing so;\n(d) the value of the claimant’s property and any income derived from such property, or from the claimant's own earnings or from any other source;\n(e) the number of persons entitled to maintenance under this Act.\n(3) In determining the amount of maintenance, if any, to be awarded to a dependent under this Act, regard shall be had to―\n(a) the net value of the estate of the deceased after providing for the payment of his debts;\n(b) the provision, if any, made under a will of the deceased in respect of the dependant;\n(c) the degree of relationship between the two;\n(d) the reasonable wants of the dependant;\n(e) the past relations between the dependant and the deceased;\n(f) the value of the property of the dependant and any income derived from such property; or from his or her earnings or from any other source;\n(g) the number of dependants entitled to maintenance under this Act.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 23 - Amount of maintenance.",
    "metaTitle": "Section 23 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 24",
    "sectionNo": "24",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Claimant to maintenance should be a Hindu.",
    "description": "24. Claimant to maintenance should be a Hindu.―No person shall be entitled to claim maintenance under this Chapter if he or she has ceased to be a Hindu by conversion to another religion.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 24 - Claimant to maintenance should be a Hindu.",
    "metaTitle": "Section 24 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 25",
    "sectionNo": "25",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Amount of maintenance may be altered on change of circumstances.",
    "description": "25. Amount of maintenance may be altered on change of circumstances.―The amount of maintenance, whether fixed by a decree of court or by agreement, either before or after the commencement of this Act, may be altered subsequently if there is a material change in the circumstances justifying such alteration.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 25 - Amount of maintenance may be altered on change of circumstances.",
    "metaTitle": "Section 25 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 26",
    "sectionNo": "26",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Debts to have priority.",
    "description": "26. Debts to have priority.―Subject to the provisions contained in section 27 debts of every description contracted or payable by the deceased shall have priority over the claims of his dependants for maintenance under this Act.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 26 - Debts to have priority.",
    "metaTitle": "Section 26 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 27",
    "sectionNo": "27",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Maintenance when to be a charge.",
    "description": "27. Maintenance when to be a charge.―A dependant’s claim for maintenance under this Act shall not be a charge on the estate of the deceased or any portion thereof, unless one has been created by the will of the deceased, by a decree of court, by agreement between the dependant and the owner of the estate or portion, or otherwise.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 27 - Maintenance when to be a charge.",
    "metaTitle": "Section 27 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 28",
    "sectionNo": "28",
    "chapterNo": 3,
    "chapterRoman": "III",
    "chapterName": "MAINTENANCE",
    "title": "Effect of transfer of property on right to maintenance.",
    "description": "28. Effect of transfer of property on right to maintenance.―Where a dependant has a right to receive maintenance out of an estate and such estate or any part thereof is transferred, the right to receive maintenance may be enforced against the transferee if the transferee has notice of the right, or if the transfer is gratuitous; but not against the transferee for consideration and without notice of the right.",
    "metaData": "MAINTENANCE",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 28 - Effect of transfer of property on right to maintenance.",
    "metaTitle": "Section 28 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 29",
    "sectionNo": "29",
    "chapterNo": 4,
    "chapterRoman": "IV",
    "chapterName": "REPEALS AND SAVINGS",
    "title": "[Repeals.]",
    "description": "29. [Repeals.]―Rep. by the Repealing and Amending Act, 1960 (58 of 1960), s. 2 and the First Schedule (w.e.f. 26-11-1960).",
    "metaData": "REPEALS AND SAVINGS",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 29 - [Repeals.]",
    "metaTitle": "Section 29 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  },
  {
    "section": "Section 30",
    "sectionNo": "30",
    "chapterNo": 4,
    "chapterRoman": "IV",
    "chapterName": "REPEALS AND SAVINGS",
    "title": "Savings.",
    "description": "30. Savings.―Nothing contained in this Act shall affect any adoption made before the commencement of this Act, and the validity and effect of any such adoption shall be determined as if this Act had not been passed.",
    "metaData": "REPEALS AND SAVINGS",
    "metaDescription": "THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956 Section 30 - Savings.",
    "metaTitle": "Section 30 - THE HINDU ADOPTIONS AND MAINTENANCE ACT, 1956"
  }
];
